version: "3.9"

services:
  # web:
  #   container_name: web
  #   build: ./web
  #   network_mode: bridge
  #   ports:
  #     - 3000:3000

#  api:
#    container_name: api
#    build: ./api
#    network_mode: bridge
#    ports:
#      - 8080:8080
#    restart: unless-stopped
#    depends_on:
#      - db
#    links:
#      - db
  db:
    container_name: db
    image: postgres:14-alpine
    network_mode: bridge
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=the_survey_revision
      - POSTGRES_USER=the_survey_revision
      - POSTGRES_DB=the_survey_revision
    restart: unless-stopped

  redis-master:
    container_name: redis-master
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - redis-network
    ports:
      - '6379:6379'

  redis-slave-1:
    container_name: redis-slave-1
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - redis-master
    networks:
      - redis-network
    ports:
      - '6380:6379'

  redis-slave-2:
    container_name: redis-slave-2
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - redis-master
    networks:
      - redis-network
    ports:
      - '6381:6379'

  redis-sentinel-1:
    container_name: redis-sentinel-1
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=60000
      - REDIS_SENTINEL_PARALLEL_SYNCS=1
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=2
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - redis-network
    ports:
      - '26379:26379'

  redis-sentinel-2:
    container_name: redis-sentinel-2
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=60000
      - REDIS_SENTINEL_PARALLEL_SYNCS=1
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=2
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - redis-network
    ports:
      - '26380:26379'

  redis-sentinel-3:
    container_name: redis-sentinel-3
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=60000
      - REDIS_SENTINEL_PARALLEL_SYNCS=1
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=2
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - redis-network
    ports:
      - '26381:26379'

networks:
  redis-network:
    driver: bridge

volumes:
  postgres: {}
