server:
  port: 8080
  servlet:
    context-path: /v1

springdoc:
  default-produces-media-type: "application/json"
  swagger-ui:
    path: /docs
    enabled: true
    display-request-duration: true
  cache:
    disabled: true

spring:
  session:
    store-type: redis
    timeout: 3600
  datasource:
    url: jdbc:postgresql://localhost:5432/the_survey_revision
    username: the_survey_revision
    password: the_survey_revision
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 10000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,prometheus
  endpoint:
    health:
      show-details: always