global:
  scrape_interval: 15s
  external_labels:
    monitor: 'the-survey-monitor'

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: 'v1/actuator/prometheus'
    static_configs:
      - targets:  ['host.docker.internal:8080']
