# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: The survey Java CI with Gradle

on:
  push:
    branches: [ "feat/springboot-workflow" ]
  pull_request:
    branches: [ "feat/springboot-workflow" ]

permissions:
  contents: read

jobs:
  build:
    # Set running environment.
    runs-on: ubuntu-latest
    # Indicate Task sequence.
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate # The current release candidate if any, otherwise fallback to current
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Execute Gradle build
        run: ./gradlew clean build
